version: "2"
run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - generated
    - build
  skip-files:
    - ".*\\.gen\\.go"
    - ".*_mock\\.go"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

formatters:
  enable:
    - gofumpt
    - gci
  

linters:
  enable:
    # Core correctness
    - govet
    - errcheck
    - staticcheck
    - ineffassign

    # Code quality
    - gocritic

    # Error handling & robustness
    - errorlint
    - bodyclose
    - nilerr

    # Security
    - gosec

    # Performance & allocations
    - prealloc

  disable:
    - gocyclo         # prefer readability judgement
    - funlen          # noisy for handlers
    - godot           # stylistic
    - wsl             # whitespace-only

linters-settings:
  revive:
    rules:
      - name: var-naming
      - name: line-length-limit
        arguments: [120]
      - name: indent-error-flow
      - name: early-return
      - name: unnecessary-stmt
      - name: blank-imports
      - name: error-return
      - name: error-naming
      - name: context-as-argument
      - name: exported

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104 # errors unhandled (covered by errcheck)
      - G307 # deferring unsafe Close

  gocritic:
    enabled-tags:
      - performance
      - style
      - diagnostic
    disabled-checks:
      - hugeParam
      - commentedOutCode

  errorlint:
    errorf: true
    asserts: true
    comparison: true

  govet:
    enable:
      - shadow
    disable:
      - fieldalignment

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Ignore complexity in tests
    - path: _test\.go
      linters:
        - gocyclo
        - funlen

    # Ignore generated files
    - path: ".*\\.gen\\.go"
      linters:
        - revive
        - gosec

severity:
  default-severity: error
