CREATE TABLE paragraphs (
    id INT PRIMARY KEY DEFAULT NEXTVAL('paragraph_ids_seq'),
    uuid UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);