// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jmoiron/sqlx"
	mock "github.com/stretchr/testify/mock"
)

// NewTxRunner creates a new instance of TxRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTxRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxRunner {
	mock := &TxRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TxRunner is an autogenerated mock type for the TxRunner type
type TxRunner struct {
	mock.Mock
}

type TxRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *TxRunner) EXPECT() *TxRunner_Expecter {
	return &TxRunner_Expecter{mock: &_m.Mock}
}

// RunInTxContext provides a mock function for the type TxRunner
func (_mock *TxRunner) RunInTxContext(ctx context.Context, fn func(*sqlx.Tx) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for RunInTxContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(*sqlx.Tx) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TxRunner_RunInTxContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunInTxContext'
type TxRunner_RunInTxContext_Call struct {
	*mock.Call
}

// RunInTxContext is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(*sqlx.Tx) error
func (_e *TxRunner_Expecter) RunInTxContext(ctx interface{}, fn interface{}) *TxRunner_RunInTxContext_Call {
	return &TxRunner_RunInTxContext_Call{Call: _e.mock.On("RunInTxContext", ctx, fn)}
}

func (_c *TxRunner_RunInTxContext_Call) Run(run func(ctx context.Context, fn func(*sqlx.Tx) error)) *TxRunner_RunInTxContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(*sqlx.Tx) error
		if args[1] != nil {
			arg1 = args[1].(func(*sqlx.Tx) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TxRunner_RunInTxContext_Call) Return(err error) *TxRunner_RunInTxContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TxRunner_RunInTxContext_Call) RunAndReturn(run func(ctx context.Context, fn func(*sqlx.Tx) error) error) *TxRunner_RunInTxContext_Call {
	_c.Call.Return(run)
	return _c
}
