// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jmoiron/sqlx"
	mock "github.com/stretchr/testify/mock"
)

// NewBaseRepository creates a new instance of BaseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBaseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BaseRepository {
	mock := &BaseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BaseRepository is an autogenerated mock type for the BaseRepository type
type BaseRepository struct {
	mock.Mock
}

type BaseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *BaseRepository) EXPECT() *BaseRepository_Expecter {
	return &BaseRepository_Expecter{mock: &_m.Mock}
}

// NamedGetRow provides a mock function for the type BaseRepository
func (_mock *BaseRepository) NamedGetRow(ctx context.Context, tx *sqlx.Tx, query string, dest interface{}, arg interface{}) error {
	ret := _mock.Called(ctx, tx, query, dest, arg)

	if len(ret) == 0 {
		panic("no return value specified for NamedGetRow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string, interface{}, interface{}) error); ok {
		r0 = returnFunc(ctx, tx, query, dest, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BaseRepository_NamedGetRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NamedGetRow'
type BaseRepository_NamedGetRow_Call struct {
	*mock.Call
}

// NamedGetRow is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - query string
//   - dest interface{}
//   - arg interface{}
func (_e *BaseRepository_Expecter) NamedGetRow(ctx interface{}, tx interface{}, query interface{}, dest interface{}, arg interface{}) *BaseRepository_NamedGetRow_Call {
	return &BaseRepository_NamedGetRow_Call{Call: _e.mock.On("NamedGetRow", ctx, tx, query, dest, arg)}
}

func (_c *BaseRepository_NamedGetRow_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, query string, dest interface{}, arg interface{})) *BaseRepository_NamedGetRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqlx.Tx
		if args[1] != nil {
			arg1 = args[1].(*sqlx.Tx)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 interface{}
		if args[3] != nil {
			arg3 = args[3].(interface{})
		}
		var arg4 interface{}
		if args[4] != nil {
			arg4 = args[4].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *BaseRepository_NamedGetRow_Call) Return(err error) *BaseRepository_NamedGetRow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BaseRepository_NamedGetRow_Call) RunAndReturn(run func(ctx context.Context, tx *sqlx.Tx, query string, dest interface{}, arg interface{}) error) *BaseRepository_NamedGetRow_Call {
	_c.Call.Return(run)
	return _c
}

// NamedQueryRow provides a mock function for the type BaseRepository
func (_mock *BaseRepository) NamedQueryRow(ctx context.Context, tx *sqlx.Tx, query string, dest interface{}, arg interface{}) error {
	ret := _mock.Called(ctx, tx, query, dest, arg)

	if len(ret) == 0 {
		panic("no return value specified for NamedQueryRow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string, interface{}, interface{}) error); ok {
		r0 = returnFunc(ctx, tx, query, dest, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BaseRepository_NamedQueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NamedQueryRow'
type BaseRepository_NamedQueryRow_Call struct {
	*mock.Call
}

// NamedQueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - query string
//   - dest interface{}
//   - arg interface{}
func (_e *BaseRepository_Expecter) NamedQueryRow(ctx interface{}, tx interface{}, query interface{}, dest interface{}, arg interface{}) *BaseRepository_NamedQueryRow_Call {
	return &BaseRepository_NamedQueryRow_Call{Call: _e.mock.On("NamedQueryRow", ctx, tx, query, dest, arg)}
}

func (_c *BaseRepository_NamedQueryRow_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, query string, dest interface{}, arg interface{})) *BaseRepository_NamedQueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqlx.Tx
		if args[1] != nil {
			arg1 = args[1].(*sqlx.Tx)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 interface{}
		if args[3] != nil {
			arg3 = args[3].(interface{})
		}
		var arg4 interface{}
		if args[4] != nil {
			arg4 = args[4].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *BaseRepository_NamedQueryRow_Call) Return(err error) *BaseRepository_NamedQueryRow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BaseRepository_NamedQueryRow_Call) RunAndReturn(run func(ctx context.Context, tx *sqlx.Tx, query string, dest interface{}, arg interface{}) error) *BaseRepository_NamedQueryRow_Call {
	_c.Call.Return(run)
	return _c
}
