// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gagansingh3785/typio-service/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// GetRandomParagraph provides a mock function for the type Repository
func (_mock *Repository) GetRandomParagraph(ctx context.Context) (*domain.Paragraph, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRandomParagraph")
	}

	var r0 *domain.Paragraph
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*domain.Paragraph, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *domain.Paragraph); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Paragraph)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetRandomParagraph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRandomParagraph'
type Repository_GetRandomParagraph_Call struct {
	*mock.Call
}

// GetRandomParagraph is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Repository_Expecter) GetRandomParagraph(ctx interface{}) *Repository_GetRandomParagraph_Call {
	return &Repository_GetRandomParagraph_Call{Call: _e.mock.On("GetRandomParagraph", ctx)}
}

func (_c *Repository_GetRandomParagraph_Call) Run(run func(ctx context.Context)) *Repository_GetRandomParagraph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repository_GetRandomParagraph_Call) Return(paragraph *domain.Paragraph, err error) *Repository_GetRandomParagraph_Call {
	_c.Call.Return(paragraph, err)
	return _c
}

func (_c *Repository_GetRandomParagraph_Call) RunAndReturn(run func(ctx context.Context) (*domain.Paragraph, error)) *Repository_GetRandomParagraph_Call {
	_c.Call.Return(run)
	return _c
}

// InsertParagraph provides a mock function for the type Repository
func (_mock *Repository) InsertParagraph(ctx context.Context, paragraph domain.Paragraph) (*domain.Paragraph, error) {
	ret := _mock.Called(ctx, paragraph)

	if len(ret) == 0 {
		panic("no return value specified for InsertParagraph")
	}

	var r0 *domain.Paragraph
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Paragraph) (*domain.Paragraph, error)); ok {
		return returnFunc(ctx, paragraph)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Paragraph) *domain.Paragraph); ok {
		r0 = returnFunc(ctx, paragraph)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Paragraph)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Paragraph) error); ok {
		r1 = returnFunc(ctx, paragraph)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_InsertParagraph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertParagraph'
type Repository_InsertParagraph_Call struct {
	*mock.Call
}

// InsertParagraph is a helper method to define mock.On call
//   - ctx context.Context
//   - paragraph domain.Paragraph
func (_e *Repository_Expecter) InsertParagraph(ctx interface{}, paragraph interface{}) *Repository_InsertParagraph_Call {
	return &Repository_InsertParagraph_Call{Call: _e.mock.On("InsertParagraph", ctx, paragraph)}
}

func (_c *Repository_InsertParagraph_Call) Run(run func(ctx context.Context, paragraph domain.Paragraph)) *Repository_InsertParagraph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Paragraph
		if args[1] != nil {
			arg1 = args[1].(domain.Paragraph)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_InsertParagraph_Call) Return(paragraph1 *domain.Paragraph, err error) *Repository_InsertParagraph_Call {
	_c.Call.Return(paragraph1, err)
	return _c
}

func (_c *Repository_InsertParagraph_Call) RunAndReturn(run func(ctx context.Context, paragraph domain.Paragraph) (*domain.Paragraph, error)) *Repository_InsertParagraph_Call {
	_c.Call.Return(run)
	return _c
}
