// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gagansingh3785/typio-service/builders"
	"github.com/gagansingh3785/typio-service/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewParagraphsBuilder creates a new instance of ParagraphsBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParagraphsBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParagraphsBuilder {
	mock := &ParagraphsBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ParagraphsBuilder is an autogenerated mock type for the ParagraphsBuilder type
type ParagraphsBuilder struct {
	mock.Mock
}

type ParagraphsBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *ParagraphsBuilder) EXPECT() *ParagraphsBuilder_Expecter {
	return &ParagraphsBuilder_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type ParagraphsBuilder
func (_mock *ParagraphsBuilder) Build(ctx context.Context, resp builders.ParagraphResponseAsync) (*domain.Paragraph, error) {
	ret := _mock.Called(ctx, resp)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 *domain.Paragraph
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, builders.ParagraphResponseAsync) (*domain.Paragraph, error)); ok {
		return returnFunc(ctx, resp)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, builders.ParagraphResponseAsync) *domain.Paragraph); ok {
		r0 = returnFunc(ctx, resp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Paragraph)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, builders.ParagraphResponseAsync) error); ok {
		r1 = returnFunc(ctx, resp)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ParagraphsBuilder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type ParagraphsBuilder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - ctx context.Context
//   - resp builders.ParagraphResponseAsync
func (_e *ParagraphsBuilder_Expecter) Build(ctx interface{}, resp interface{}) *ParagraphsBuilder_Build_Call {
	return &ParagraphsBuilder_Build_Call{Call: _e.mock.On("Build", ctx, resp)}
}

func (_c *ParagraphsBuilder_Build_Call) Run(run func(ctx context.Context, resp builders.ParagraphResponseAsync)) *ParagraphsBuilder_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 builders.ParagraphResponseAsync
		if args[1] != nil {
			arg1 = args[1].(builders.ParagraphResponseAsync)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ParagraphsBuilder_Build_Call) Return(paragraph *domain.Paragraph, err error) *ParagraphsBuilder_Build_Call {
	_c.Call.Return(paragraph, err)
	return _c
}

func (_c *ParagraphsBuilder_Build_Call) RunAndReturn(run func(ctx context.Context, resp builders.ParagraphResponseAsync) (*domain.Paragraph, error)) *ParagraphsBuilder_Build_Call {
	_c.Call.Return(run)
	return _c
}

// GetAsycChannel provides a mock function for the type ParagraphsBuilder
func (_mock *ParagraphsBuilder) GetAsycChannel(ctx context.Context) chan builders.ParagraphResponseAsync {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAsycChannel")
	}

	var r0 chan builders.ParagraphResponseAsync
	if returnFunc, ok := ret.Get(0).(func(context.Context) chan builders.ParagraphResponseAsync); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan builders.ParagraphResponseAsync)
		}
	}
	return r0
}

// ParagraphsBuilder_GetAsycChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAsycChannel'
type ParagraphsBuilder_GetAsycChannel_Call struct {
	*mock.Call
}

// GetAsycChannel is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ParagraphsBuilder_Expecter) GetAsycChannel(ctx interface{}) *ParagraphsBuilder_GetAsycChannel_Call {
	return &ParagraphsBuilder_GetAsycChannel_Call{Call: _e.mock.On("GetAsycChannel", ctx)}
}

func (_c *ParagraphsBuilder_GetAsycChannel_Call) Run(run func(ctx context.Context)) *ParagraphsBuilder_GetAsycChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ParagraphsBuilder_GetAsycChannel_Call) Return(paragraphResponseAsyncCh chan builders.ParagraphResponseAsync) *ParagraphsBuilder_GetAsycChannel_Call {
	_c.Call.Return(paragraphResponseAsyncCh)
	return _c
}

func (_c *ParagraphsBuilder_GetAsycChannel_Call) RunAndReturn(run func(ctx context.Context) chan builders.ParagraphResponseAsync) *ParagraphsBuilder_GetAsycChannel_Call {
	_c.Call.Return(run)
	return _c
}
