// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gagansingh3785/typio-service/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewParagraphService creates a new instance of ParagraphService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParagraphService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParagraphService {
	mock := &ParagraphService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ParagraphService is an autogenerated mock type for the ParagraphService type
type ParagraphService struct {
	mock.Mock
}

type ParagraphService_Expecter struct {
	mock *mock.Mock
}

func (_m *ParagraphService) EXPECT() *ParagraphService_Expecter {
	return &ParagraphService_Expecter{mock: &_m.Mock}
}

// GetRandomParagraph provides a mock function for the type ParagraphService
func (_mock *ParagraphService) GetRandomParagraph(ctx context.Context) (*domain.Paragraph, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRandomParagraph")
	}

	var r0 *domain.Paragraph
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*domain.Paragraph, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *domain.Paragraph); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Paragraph)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ParagraphService_GetRandomParagraph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRandomParagraph'
type ParagraphService_GetRandomParagraph_Call struct {
	*mock.Call
}

// GetRandomParagraph is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ParagraphService_Expecter) GetRandomParagraph(ctx interface{}) *ParagraphService_GetRandomParagraph_Call {
	return &ParagraphService_GetRandomParagraph_Call{Call: _e.mock.On("GetRandomParagraph", ctx)}
}

func (_c *ParagraphService_GetRandomParagraph_Call) Run(run func(ctx context.Context)) *ParagraphService_GetRandomParagraph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ParagraphService_GetRandomParagraph_Call) Return(paragraph *domain.Paragraph, err error) *ParagraphService_GetRandomParagraph_Call {
	_c.Call.Return(paragraph, err)
	return _c
}

func (_c *ParagraphService_GetRandomParagraph_Call) RunAndReturn(run func(ctx context.Context) (*domain.Paragraph, error)) *ParagraphService_GetRandomParagraph_Call {
	_c.Call.Return(run)
	return _c
}
